# Site settings
author: Yani Asari
title: Coding Calling 
header-img: img/home-bg.png
email: yani.iman1@gmail.com
copyright_name: Yani Asari
description: > # this means to ignore newlines until "baseurl:"
  A day in the life of a coding newb
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: yi_tweets
github_username:  yani82

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
